In [1]:
import numpy as np

In [2]:
## Numpy arrays

In [3]:
bemimListem =[20,30,40]

In [5]:
type(bemimListem)

list

In [8]:
np.array(bemimListem)

numpy.ndarray

In [9]:
matrixListesi= [[10,20,30], [20,30,40]]

In [11]:
matrixListesi [0][0]

10

In [12]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40]])

In [13]:
## arange (sayı dizer)

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [16]:
## zeros

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [22]:
##linspace (eşit aralıklı sayılar oluşturur)

In [23]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [24]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [25]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [26]:
## eye (identitiy matrix oluşturur)

In [27]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
## random kütüphanesi

In [29]:
np.random.randn(8)

array([ 1.11304013, -0.11017587,  0.00312405, -0.17304892, -0.66736077,
        2.04474271, -0.64897645,  0.72471544])

In [30]:
np.random.randn(8,8)

array([[ 1.00557638, -1.10477267,  1.03871185, -0.65837529,  0.99647856,
        -0.28426835, -0.46541683,  0.9889864 ],
       [ 1.09096866,  0.18895846,  0.46633617, -0.79926043,  1.23625162,
        -0.20502368,  2.7692567 , -1.5285886 ],
       [-0.60153395, -1.47799678,  0.09658237, -1.05556156,  0.4582506 ,
        -1.42830021, -1.4875017 ,  0.29239598],
       [ 0.17385235,  1.76267608, -1.37986944, -0.41222193,  0.0490571 ,
        -0.18258113, -0.90890858, -2.05907618],
       [-0.95769462, -1.33054664, -0.66309473,  1.36568302, -0.28457309,
         0.66672119,  0.46337529, -0.76427317],
       [-1.04153763, -1.27969189, -0.59266025, -0.58933557,  0.14085403,
        -1.13582831, -1.21268959, -0.10906309],
       [ 0.52557036,  1.16691375, -0.5491848 , -0.25901679,  0.08024813,
        -0.07004899, -0.25159581, -0.03731844],
       [ 1.15155672,  1.72611582, -0.47930188,  0.69318154, -1.14511286,
         0.97532483,  1.01788868, -1.88893276]])

In [34]:
np.random.randint(1,10)  
#1 den 10a kadar herhangi bir sayıyı döndürür.

3

In [40]:
np.random.randint(10,30,5)
# 10 dan 30a kadar rastgele 5 sayı döndürür.

array([26, 20, 13, 27, 22])

In [37]:
benimNumoyDizim= np.arange(30)

In [38]:
benimNumoyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

## numpy dizi metotları


In [42]:
benimNumoyDizim.reshape(5,6)
## matrise çevirir

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
benimNumoyDizim.max()

29

In [45]:
benimNumoyDizim.min()

0

In [46]:
benimNumoyDizim.argmax()
##maximum değerin hangi indexte bulunduğunu söyler

29

In [47]:
benimNumoyDizim.argmin()

0

In [48]:
benimNumoyDizim.shape

(30,)

In [49]:
reshapeDizim= benimNumoyDizim.reshape(5,6)

In [51]:
reshapeDizim.shape
## dizinin şekli hakkında bilgi verir

(5, 6)