import numpy as np

In [6]:
benimDizim=np.arange(0,15)

In [7]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
benimDizim[5]

5

In [10]:
benimDizim[3:5]

array([3, 4])

In [11]:
benimDizim[3:8] = -5

In [12]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [13]:
baskaDizi= np.arange(0,24)

In [14]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [18]:
slicingDizisi = baskaDizi [4:9]

In [19]:
slicingDizisi

array([4, 5, 6, 7, 8])

In [20]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
slicingDizisi [:] =700

In [22]:
slicingDizisi

array([700, 700, 700, 700, 700])

In [23]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [25]:
ornekDizi= np.arange(0,24)

In [26]:
ornekDizicopy= ornekDizi.copy()

In [27]:
ornekDizicopy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [28]:
ornekDizicopySlicing=ornekDizicopy[3:6]

In [29]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

## matrix

In [34]:
ornekMatrixDizisi =np.array(ornekDizi)

In [43]:
ornek= ornekMatrixDizisi.reshape(6,4)

In [45]:
ornek[1:,2]
##1. indexin içindeki 2. indexten itibaren her indexin 2. indexini tek arraye topşlar

array([ 6, 10, 14, 18, 22])

In [44]:
ornek

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [46]:
ornek[2:,2]

array([10, 14, 18, 22])

In [47]:
ornek[3:,2]

array([14, 18, 22])

In [49]:
ornek[2:, 3]

array([11, 15, 19, 23])

In [50]:
yeniListe =np.arange(0,27)

In [51]:
yeniliste = np.array(yeniListe)

In [52]:
yeni= yeniliste.reshape(9,3)

In [53]:
yeni[[4,2,0]]
## listedeki indexlere göre matris oluşturur

array([[12, 13, 14],
       [ 6,  7,  8],
       [ 0,  1,  2]])

In [54]:
yeni

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26]])

## Operasyonlar

In [58]:
yeniBirDizi =np.random.randint(1,100,20)

In [59]:
yeniBirDizi

array([ 5, 50, 72, 15, 51,  4, 93, 46, 34, 81,  8, 31, 86, 44, 29, 25, 54,
       63, 15, 59])

In [61]:
yeniBirDizi > 24

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [62]:
sonuc= yeniBirDizi > 24

In [63]:
sonuc

array([False,  True,  True, False,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
       False,  True])

In [64]:
yeniBirDizi[sonuc]

array([50, 72, 51, 93, 46, 34, 81, 31, 86, 44, 29, 25, 54, 63, 59])

In [65]:
sonDizi= np.arange (0,24)

In [66]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [67]:
sonDizi+sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [68]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [69]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [71]:
sonDizi / sonDizi

# 0 0a bölünmeyeceği için uyarı verdi.

C:\Users\Monster\AppData\Local\Temp\ipykernel_15600\1312094733.py:1: RuntimeWarning: invalid value encountered in divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [72]:
np.sqrt (sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [73]:
np.max(sonDizi)

23

In [74]:
np.min(sonDizi)

0