In [7]:
import pandas as pd

In [8]:
import numpy as np

In [9]:
np.random.randn(4,3)

array([[-0.939913  ,  0.50113876, -1.81786602],
       [ 1.94446725, -1.09984586,  0.79594093],
       [ 0.92780639, -2.33725281, -0.29294846],
       [-1.05618166, -1.209918  ,  0.22734958]])

In [10]:
data = np.random.randint(0,10,(4,3))

In [11]:
data

array([[1, 5, 7],
       [5, 8, 2],
       [3, 2, 1],
       [6, 8, 3]])

In [12]:
dataFrame= pd.DataFrame(data)

In [13]:
dataFrame

0  1  2
0  1  5  7
1  5  8  2
2  3  2  1
3  6  8  3

In [14]:
data1=np.random.randn(4,3)

In [15]:
data1

array([[ 0.90902156,  1.28437968, -1.30819545],
       [-0.86079546,  0.85116199, -0.5970238 ],
       [ 0.93376638, -0.48003134,  0.23430598],
       [-0.40971747,  0.23192397, -0.55990237]])

In [16]:
dataFrame1= pd.DataFrame(data1)

In [17]:
dataFrame1

0         1         2
0  0.909022  1.284380 -1.308195
1 -0.860795  0.851162 -0.597024
2  0.933766 -0.480031  0.234306
3 -0.409717  0.231924 -0.559902

In [18]:
dataFrame1[0]

0    0.909022
1   -0.860795
2    0.933766
3   -0.409717
Name: 0, dtype: float64

In [19]:
yeniDataFrame = pd.DataFrame (data,index=["Atil","Zeynep","Atlas","Mehmet"], columns= ["Maas","Yas","Calisma Saati"])

In [20]:
yeniDataFrame

Maas  Yas  Calisma Saati
Atil       1    5              7
Zeynep     5    8              2
Atlas      3    2              1
Mehmet     6    8              3

In [21]:
yeniDataFrame["Yas"]

Atil      5
Zeynep    8
Atlas     2
Mehmet    8
Name: Yas, dtype: int32

In [22]:
yeniDataFrame["Calisma Saati"]

Atil      7
Zeynep    2
Atlas     1
Mehmet    3
Name: Calisma Saati, dtype: int32

In [23]:
yeniDataFrame[["Maas","Yas"]]

Maas  Yas
Atil       1    5
Zeynep     5    8
Atlas      3    2
Mehmet     6    8

In [24]:
yeniDataFrame.loc["Atil"]

Maas             1
Yas              5
Calisma Saati    7
Name: Atil, dtype: int32

In [25]:
yeniDataFrame.loc["Zeynep"]

Maas             5
Yas              8
Calisma Saati    2
Name: Zeynep, dtype: int32

In [26]:
yeniDataFrame.iloc[1]
#index bazlı getirir.

Maas             5
Yas              8
Calisma Saati    2
Name: Zeynep, dtype: int32

In [27]:
yeniDataFrame["Emeklilik Yasi"] = yeniDataFrame ["Yas"]+ yeniDataFrame["Yas"]

In [28]:
yeniDataFrame

Maas  Yas  Calisma Saati  Emeklilik Yasi
Atil       1    5              7              10
Zeynep     5    8              2              16
Atlas      3    2              1               4
Mehmet     6    8              3              16

In [29]:
yeniDataFrame.drop("Emeklilik Yasi", axis=1)
# sütün silmek için axisi 1 ver

Maas  Yas  Calisma Saati
Atil       1    5              7
Zeynep     5    8              2
Atlas      3    2              1
Mehmet     6    8              3

In [30]:
yeniDataFrame.drop("Mehmet", axis=0)
# satır silmek için axisi 0 ver

Maas  Yas  Calisma Saati  Emeklilik Yasi
Atil       1    5              7              10
Zeynep     5    8              2              16
Atlas      3    2              1               4

In [31]:
yeniDataFrame

Maas  Yas  Calisma Saati  Emeklilik Yasi
Atil       1    5              7              10
Zeynep     5    8              2              16
Atlas      3    2              1               4
Mehmet     6    8              3              16

In [32]:
yeniDataFrame.drop("Emeklilik Yasi", axis=1, inplace= True)
#Dataframei kalıcı olarak değiştirmek için inplace kullanıyoruz.

In [33]:
yeniDataFrame

Maas  Yas  Calisma Saati
Atil       1    5              7
Zeynep     5    8              2
Atlas      3    2              1
Mehmet     6    8              3

In [34]:
yeniDataFrame.loc["Atil"]["Maas"]

1

In [35]:
yeniDataFrame.loc["Atlas","Yas"]

2

In [36]:
yeniDataFrame

Maas  Yas  Calisma Saati
Atil       1    5              7
Zeynep     5    8              2
Atlas      3    2              1
Mehmet     6    8              3

In [37]:
booleanFrame= yeniDataFrame < 5

In [38]:
yeniDataFrame

Maas  Yas  Calisma Saati
Atil       1    5              7
Zeynep     5    8              2
Atlas      3    2              1
Mehmet     6    8              3

In [39]:
yeniDataFrame[booleanFrame]

Maas  Yas  Calisma Saati
Atil     1.0  NaN            NaN
Zeynep   NaN  NaN            2.0
Atlas    3.0  2.0            1.0
Mehmet   NaN  NaN            3.0

In [40]:
yeniDataFrame[yeniDataFrame<5]

Maas  Yas  Calisma Saati
Atil     1.0  NaN            NaN
Zeynep   NaN  NaN            2.0
Atlas    3.0  2.0            1.0
Mehmet   NaN  NaN            3.0

In [41]:
yeniDataFrame[yeniDataFrame["Yas"] > 3]

Maas  Yas  Calisma Saati
Atil       1    5              7
Zeynep     5    8              2
Mehmet     6    8              3

In [42]:
yeniDataFrame.reset_index()

index  Maas  Yas  Calisma Saati
0    Atil     1    5              7
1  Zeynep     5    8              2
2   Atlas     3    2              1
3  Mehmet     6    8              3

In [43]:
yeniDataFrame

Maas  Yas  Calisma Saati
Atil       1    5              7
Zeynep     5    8              2
Atlas      3    2              1
Mehmet     6    8              3

In [44]:
yeniIndexListesi = ["a","z","at","meh"]

In [45]:
yeniDataFrame["Yeni Index"] = yeniIndexListesi

In [46]:
yeniDataFrame

Maas  Yas  Calisma Saati Yeni Index
Atil       1    5              7          a
Zeynep     5    8              2          z
Atlas      3    2              1         at
Mehmet     6    8              3        meh

In [47]:
yeniDataFrame.set_index("Yeni Index")

Maas  Yas  Calisma Saati
Yeni Index                          
a              1    5              7
z              5    8              2
at             3    2              1
meh            6    8              3

In [48]:
yeniDataFrame

Maas  Yas  Calisma Saati Yeni Index
Atil       1    5              7          a
Zeynep     5    8              2          z
Atlas      3    2              1         at
Mehmet     6    8              3        meh

In [49]:
yeniDataFrame.set_index("Yeni Index", inplace=True)

In [50]:
yeniDataFrame.loc["a"]

Maas             1
Yas              5
Calisma Saati    7
Name: a, dtype: int32

## multi indeks

In [51]:
ilkIndexler =["Simpson", "Simpson","Simpson","South Park","South Park","South Park"]

In [52]:
icIndeksler=["Homer","Bart","Marge","Cartman","Kenny","Kyle"]

In [53]:
birlesmisIndeks = list(zip(ilkIndexler,icIndeksler))

In [54]:
birlesmisIndeks

[('Simpson', 'Homer'),
 ('Simpson', 'Bart'),
 ('Simpson', 'Marge'),
 ('South Park', 'Cartman'),
 ('South Park', 'Kenny'),
 ('South Park', 'Kyle')]

In [55]:
birlesmisIndeks = pd.MultiIndex.from_tuples(birlesmisIndeks)

In [56]:
birlesmisIndeks

MultiIndex([(   'Simpson',   'Homer'),
            (   'Simpson',    'Bart'),
            (   'Simpson',   'Marge'),
            ('South Park', 'Cartman'),
            ('South Park',   'Kenny'),
            ('South Park',    'Kyle')],
           )

In [58]:
benimCizgiFilmListem=[[40,"A"],[30,"B"],[30,"C"],[9,"D"],[10,"E"],[11,"F"]]

In [60]:
cizgiFilmNumoyDizisi = np.array(benimCizgiFilmListem)

In [63]:
cizgiFilmDataFrame = pd.DataFrame(cizgiFilmNumoyDizisi, index = birlesmisIndeks, columns = ["Yas","Meslek"])

In [64]:
cizgiFilmDataFrame

Yas Meslek
Simpson    Homer    40      A
           Bart     30      B
           Marge    30      C
South Park Cartman   9      D
           Kenny    10      E
           Kyle     11      F

In [68]:
cizgiFilmDataFrame.loc["South Park"].loc["Kenny"]

Yas       10
Meslek     E
Name: Kenny, dtype: object

In [73]:
cizgiFilmDataFrame.index.names =["Film Adı", "İsim"]

In [74]:
cizgiFilmDataFrame

Yas Meslek
Film Adı   İsim              
Simpson    Homer    40      A
           Bart     30      B
           Marge    30      C
South Park Cartman   9      D
           Kenny    10      E
           Kyle     11      F